performant-software/core-data-places

README.md
public/config.json
src/apps/search/MapView.tsx
src/apps/search/Place.tsx

Per #8:
- Add a `search.zoom_to_place` boolean config option to allow disabling `fitBoundingBox` on the place detail page. In other words, allow users to disable zooming to an individual place on selection. Searches/filters narrowing the results will still zoom as before.
Per #9:
- Add a `search.max_zoom` numeric config option for adjusting the max zoom of the map.
- Something I noticed while setting up my instance: the readme links to https://github.com/performant-software/core-data-tina-cms-content but that gives me a 404. Maybe it's a private repo? If it's been removed, we should update the readme.

Allow configuring max zoom and individual place zoom (#8, #9)

---

src/apps/search/SearchResultsList.tsx

Per #10:
- A small CSS change that introduces `line-clamp-3` Tailwind class to search results, such that result text is clamped to three lines and does not overflow the element.
- Adds the `leading-6` class as somehow line-clamp clobbers the line height; this restores the line height to `1.5rem`.

Truncate search results to 3 lines of text (#10)

---

src/apps/search/Place.tsx

Per #7:
- Fix a bug where place detail data would be appended rather than replaced, by preventing a key collision.
Two adjacent components `PlaceDetails` and `RelatedRecords` shared a `key` attribute. For whatever reason, React decided that this meant it should append a new `PlaceDetails` whenever that key changed, while keeping the old one rendered. Resolving the collision also stopped this behavior.

Prevent key collision, resolve component duplication (#7)

---

public/config.json
src/apps/search/panels/RecordPanel.tsx

Cleanup: code and example config still contained references to `search.max_zoom` when that property was changed to `map.max_zoom` in #43.

Update search.max_zoom to map.max_zoom

---

src/i18n/utils.ts
src/pages/[lang]/index.astro
tina/content/about.ts

- Updates the schema of the `about` collection in TinaCMS to allow users to add `title`, `subheader`, and `description` for each language specified in the `config.json` file, with the default locale as top level fields and other locales as nested fields (this allows compatibility with how existing project content is configured with only one language);
- Updates the `pages/[lang]/index.astro` to fetch localized text content, and default to the default locale if no localized content is defined.

Adding i18n functionality to `about` collection

---

src/components/MobileHeader.tsx
src/layouts/Footer.astro
src/layouts/Header.astro
src/layouts/Layout.astro
src/styles/index.css
src/utils/layout.ts
tailwind.config.mjs
tina/content/settings.ts

First pass at adding the ability to customize the primary color and add a logo to the header, as well as updating the footer to the new designs and allowing logos to be added to it.
For the time being after struggling a bunch to figure out how to set Tailwind colors using asynchronously fetched data, I ended up putting the customization fields in the `settings` collection rather than the `about` collection, so that they end up in the `config.json` file that's already being copied to the `public` folder at build time. This seems to work, but if we'd prefer those fields to be in the `about` collection, then it could probably be done with an additional build script that runs before `astro build` and copies the color info to somewhere Tailwind can find it. I currently don't think there's an …

Adding custom primary colors and header logo

---

src/components/PlacesMap.tsx

Fixes the behavior described in Issue #92 by stopping propagation when clicking on the controls of an embedded map (e.g. in a post), so that the place modal does not open.

Suppress modal when clicking on zoom controls

---

src/apps/search/ResultTooltip.tsx

This PR changes the source of the text in the `ResultTooltip` from `result_card.subtitle` to the first entry in `result_card.attributes`. If the `attributes` array is empty or doesn't exist, only the `title` value will be shown.

Use `result_card.attributes` array for `ResultTooltip` text

---

src/apps/search/ClearRefinementsButton.tsx
src/apps/search/Header.tsx
src/apps/search/ListView.tsx
src/apps/search/SearchLayout.tsx
src/apps/search/TableView.tsx
src/apps/search/useSelectable.ts
tailwind.config.mjs

This pull request addresses the feedback in #102 by making the following changes:
- Updates the search header bar height from 80px to 64px
- Adjusts the spacing between title and search input to `gap-x-12`
- Updates "List" and "Table" buttons to use `text-smd` font size (15px equivalent with 16px base)
- Updates title to `font-bold`
Hides the "Reset" facets button until filters have been applied
Updates the ListView and TableView to highlight selected records when detail panel is open

CDP #102 - Layout

---

src/components/LanguagePicker.tsx

Addresses Issue #107 by specifying that the text in the language picker dropdown should be black.

Making `LanguagePicker` dropdown text black

---

src/apps/search/Header.tsx

This pull request updates the facet counter to display the number of facet _values_ currently being applied, instead of the number of _fields_. Now the number will match the number of current facet pill elements.

CDP #108 - Facet counter

---

.env.example
tina/database.ts

This pull request adds the ability to define a `MONGODB_COLLECTION_NAME` environment variable, which will be used as the name of the collection in the Mongo Database. This will allow us to use separate MongoDB collections for the production, preview, and branch deploys of a single site.
**Note:** We couldn't just use a unique value because the MongoDB collections are never removed. Deploy previews for the same site will share the same collection. This has the ability to cause conflicts, but will not cause conflicts with the production version of the site.

CDP #120 - MongoDB collection name

---

src/layouts/Footer.astro

In the case that the primary color is dark, the text on the footer buttons ends up white-on-white (see Issue #126 ). This PR fixes that by making the text black in the non-hover state.

Fixing button text color in footer

---

src/loaders/api/helpers.ts

This PR adds the `per_page=-1` param to the URL that `getRelation` uses to fetch related records, disabling the per-page limit. Previously, it was limited to Core Data's default pagination limit of 10.
In the long run, we should migrate the loader to use `@performant-software/core_data`'s service helpers, unblocked by https://github.com/performant-software/react-components/pull/475. But this is a really quick short-term fix.

Disable pagination on relations Core Data API request

---

tina/components/MapInput.tsx
tina/components/TableInput.tsx

This pull request fixes two separate issues with the MapInput and TableInput components:
We were not correctly getting the geometry data when the `search.map.geometry` attribute was a path to a nested record (e.g. for non-place records).
We were not using the search-specific configuration to pull the table attributes from the config.

CDP #117 - Data visualizations

---

tina/content/settings.ts

Per #162:
- Add the `map` object back to Tina search settings 
Noticed this when I edited the timeline config in Tina for the scavenger hunt site, looks like this was accidentally removed during the big config update.

Add "map" object back to tina settings collection (#162)

---

.env.example
src/content.config.ts
src/layouts/Footer.astro
src/types.ts

This pull request updates the `Footer` component to hide the Core Data and TinaCMS login buttons when we're building the site in "static" mode. 
It also adds the optional `USE_CONTENT_CACHE` environment variable to allow the site to be built in "static" mode without running the content loaders. This is useful in a dev environment when the dev server may be restarted multiple times.

CDP #151 - Disable TinaCMS

---

src/apps/search/SearchRoutes.tsx

After following a bunch of red herring error messages in the console, I discovered that #155 was caused by a typo in the `SearchRoutes` component. It was matching `/work` instead of `/works`. The `/items` route had the same issue, so I also fixed that one.

Fix typo in works pane route

---

src/apps/search/SearchLayout.tsx

Per #164:
- Add `bottomOpen` to dependencies for the `setBoundingBoxOptions` `useEffect` call (instead of `view`, whose value is not read by it and is used in the calculation of `bottomOpen`)

Ensure map bounding box updated when timeline is opened (#164)

---

src/apps/posts/PlaceInsert.tsx
src/pages/[lang]/posts/[slug].astro
src/visualizations/Table.tsx

This pull request fixes a bug where the `margin: auto` CSS was causing an issue within a flexbox container for the post content. The solution was to add the `w-full` class to the container in order to set the width to "100%".
This pull request also fixes an issue with the map component not taking up the entire width of the container. To fix that, I removed the `mx-auto` class on the child containers and added `w-full`.
Finally, this pull request removes the horizontal padding on the Table visualization container to align the table with the header/content.

CDP #152 - Post content

---

src/pages/[lang]/posts/index.astro
tina/components/TimelineInput.tsx
tina/content/visualizations.ts
tina/utils/visualizations.ts

This pull request fixes an issue where the Timeline embed was not available in a post record unless the `event_path` configuration option was explicitly set, which should not be necessary for event-based indexes. The solution was to add a utility method to check whether to include the Timeline, which will be available to the two places that use it.
Additionally, this pull request fixes a layout issue with the posts index page.

CDP #177 - Timeline embed

---

src/components/Card.astro

During work on the record detail pages the default background for the `main` node of the `layout` was changed from `neutral-light` to `white`; accordingly, the `card` component that's used for the index pages for paths and posts should be updated to `neutral-light` to maintain contrast. This PR does that, with a few other little tweaks to avoid having things like `gray-100` on top of `neutral-light`.

Fixing `card` background to `neutral-light`

---

src/apps/pages/RecordDetail/PlaceMap.tsx
src/apps/pages/RecordDetail/index.astro
src/pages/[lang]/events/[uuid]/index.astro
src/pages/[lang]/instances/[uuid]/index.astro
src/pages/[lang]/items/[uuid]/index.astro
src/pages/[lang]/organizations/[uuid]/index.astro
src/pages/[lang]/people/[uuid]/index.astro
src/pages/[lang]/places/[uuid]/index.astro
src/pages/[lang]/works/[uuid]/index.astro
src/services/coreData/base.ts
src/utils/detailPages.ts

This PR adds cover images to all models, and adds a related places map in the cover banner for non-place records.
When both a cover image and related places exist, the cover image takes up 30% of the width and the map takes up 70%. If only one is available, that component takes 100% of the width.

Cover images for detail pages

---

src/apps/search/RangeFacet.tsx

This pull request adds the `bg-neutral-200` class to the slider track element to make it visible against the gray background.

CDP #195 - Slider track

---

src/services/coreData/factory.ts

Addresses Issue #208 by adding the missing `media_contents` case to `services/coreData/factory.ts`.

Adding `media_contents` to services factory

---

scripts/build.config.mjs
scripts/build.fields.mjs
scripts/build.mjs
scripts/build.search.mjs

This pull request fixes an issue in the custom build scripts which were preventing some labels from displaying correctly. Previously, each build script (`build.<type>.mjs`) was run indepdently as a Node process. The refactor in the previous release pulled them all into a single script. The `build.fields.mjs` and `build.search.mjs` scripts were importing the `config.json`, which caused a discrepency because the new build script was also writing to `config.json`.
The solution was to return the JSON data from the `build.config.mjs` script and pass it as an argument to the other scripts, rather than using an `import` statement.

CDP #218 - Labels

---

astro.config.mjs
src/content.config.ts
src/env.d.ts
src/layouts/Layout.astro
src/pages/[lang]/search/[name]/index.astro
src/pages/api/session/[key]/[id].ts
src/pages/api/session/[key]/index.ts
src/services/coreData/factory.ts

This pull request fixes the following issues with building a static version of the site:
- Adds the missing `getStaticPaths` functions to the `/api/session/*` pages
- Updates `/services/coreData/factory` to _not_ return the media contents service, as this site does not provide API endpoints for that model
- Updates to use type-safe environment variables for `STATIC_BUILD` and `USE_CONTENT_CACHE`

CDP #236 - Static site

---

src/apps/search/panels/BasePanel.tsx
src/apps/search/panels/Place.tsx
src/loaders/coreData/helpers.ts

A hotfix patch to fix the issue of the map search page crashing when a place with null geometry is opened in the detail panel.
Note that this does not fix the issue at the source; there should also be an update done to the `react-components` library to fix the `toFeatureCollection` method to fail more gracefully when passed null geometry.

v1.4.1 null geometry hotfix
